import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReduxProvider } from './modules/provider'
import { MotionWrapper } from './modules/motionwrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'GISMo Family Day',
  description: 'Generated by the great me, the one and only, praise be unto me!',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}><ReduxProvider><MotionWrapper>{children}</MotionWrapper></ReduxProvider></body>
    </html>
  )
}
